"""Runtime-neutral execution contracts and adapters."""

from relay_engine.agent_runtime.errors import AgentRuntimeError
from relay_engine.agent_runtime.models import (
    CredentialRef,
    EventContinuity,
    RuntimeCancelRequest,
    RuntimeCapability,
    RuntimeContinuityReason,
    RuntimeContinuityState,
    RuntimeControlAck,
    RuntimeControlAckState,
    RuntimeDescriptor,
    RuntimeEventEnvelope,
    RuntimeEventType,
    RuntimeExecutionBasis,
    RuntimeExecutionHandle,
    RuntimeExecutionInspection,
    RuntimeExecutionLimits,
    RuntimeExecutionRequest,
    RuntimeFailure,
    RuntimeFailureCategory,
    RuntimeIdentityCompleteness,
    RuntimeInputAttachmentRef,
    RuntimeInputPayload,
    RuntimeInvocationRef,
    RuntimePermissionProfileRef,
    RuntimeProvenance,
    RuntimeSelection,
    RuntimeSessionBinding,
    RuntimeSessionRef,
    RuntimeStatus,
    RuntimeUsage,
    RuntimeWorkspaceAttachment,
    canonical_execution_basis_json,
    digest_execution_basis,
)
from relay_engine.agent_runtime.protocol import AgentRuntime

__all__ = [
    "AgentRuntime",
    "AgentRuntimeError",
    "CredentialRef",
    "EventContinuity",
    "RuntimeCapability",
    "RuntimeCancelRequest",
    "RuntimeContinuityReason",
    "RuntimeContinuityState",
    "RuntimeControlAck",
    "RuntimeControlAckState",
    "RuntimeDescriptor",
    "RuntimeEventEnvelope",
    "RuntimeEventType",
    "RuntimeExecutionBasis",
    "RuntimeExecutionHandle",
    "RuntimeExecutionInspection",
    "RuntimeExecutionLimits",
    "RuntimeExecutionRequest",
    "RuntimeFailure",
    "RuntimeFailureCategory",
    "RuntimeIdentityCompleteness",
    "RuntimeInputAttachmentRef",
    "RuntimeInputPayload",
    "RuntimeInvocationRef",
    "RuntimePermissionProfileRef",
    "RuntimeProvenance",
    "RuntimeSelection",
    "RuntimeSessionBinding",
    "RuntimeSessionRef",
    "RuntimeStatus",
    "RuntimeUsage",
    "RuntimeWorkspaceAttachment",
    "canonical_execution_basis_json",
    "digest_execution_basis",
]
