"""Explicit SQLite persistence for accepted Relay engineering state."""

from relay_engine.persistence.database import RelayDatabase, open_database
from relay_engine.persistence.errors import (
    ConcurrencyConflict,
    DatabaseUnavailable,
    MigrationError,
    PersistenceError,
    PersistenceIntegrityError,
)
from relay_engine.persistence.migrations import (
    DEFAULT_MIGRATIONS,
    INITIAL_MIGRATION,
    Migration,
    apply_migrations,
    verify_schema,
)
from relay_engine.persistence.records import ExecutionRecord, GateEvaluationRecord
from relay_engine.persistence.store import (
    execute_and_persist_handover,
    insert_artifact,
    insert_authorization_grant,
    insert_baseline,
    insert_decision,
    insert_evidence,
    insert_gate_evaluation_record,
    insert_handover_gate,
    insert_human_decision,
    insert_project,
    insert_slice,
    load_artifact,
    load_authorization_grant,
    load_baseline,
    load_current_lifecycle,
    load_decision,
    load_evidence,
    load_execution_record,
    load_execution_records,
    load_gate_evaluation_record,
    load_gate_evaluation_records,
    load_handover_gate,
    load_handover_gates,
    load_human_decision,
    load_lifecycle_events,
    load_project,
    load_slice,
    persist_lifecycle_change,
    persist_lifecycle_initialization,
    verify_slice_history,
)

__all__ = [
    "ConcurrencyConflict",
    "DEFAULT_MIGRATIONS",
    "DatabaseUnavailable",
    "ExecutionRecord",
    "GateEvaluationRecord",
    "INITIAL_MIGRATION",
    "Migration",
    "MigrationError",
    "PersistenceError",
    "PersistenceIntegrityError",
    "RelayDatabase",
    "apply_migrations",
    "execute_and_persist_handover",
    "insert_artifact",
    "insert_authorization_grant",
    "insert_baseline",
    "insert_decision",
    "insert_evidence",
    "insert_gate_evaluation_record",
    "insert_handover_gate",
    "insert_human_decision",
    "insert_project",
    "insert_slice",
    "load_artifact",
    "load_authorization_grant",
    "load_baseline",
    "load_current_lifecycle",
    "load_decision",
    "load_evidence",
    "load_execution_record",
    "load_execution_records",
    "load_gate_evaluation_record",
    "load_gate_evaluation_records",
    "load_handover_gate",
    "load_handover_gates",
    "load_human_decision",
    "load_lifecycle_events",
    "load_project",
    "load_slice",
    "open_database",
    "persist_lifecycle_change",
    "persist_lifecycle_initialization",
    "verify_schema",
    "verify_slice_history",
]
