"""Provider-neutral, deterministic handover governance."""

from relay_engine.governance.engine import evaluate_handover_gates, execute_handover
from relay_engine.governance.errors import (
    GovernanceError,
    HandoverNotExecutable,
    InvalidGateSet,
    InvalidHandoverContext,
)
from relay_engine.governance.models import (
    AuthorizationGrant,
    AuthorizationId,
    ChangeSurfaceStatus,
    EvaluationOutcome,
    GateEvaluation,
    GateReason,
    GateReasonCode,
    GateReasonKind,
    GateRevisionRef,
    HandoverContext,
    HandoverGate,
    HandoverGateId,
    HandoverPolicy,
    HumanApprovalDecision,
    HumanApprovalValue,
    HumanChoiceDecision,
    HumanDecisionId,
    HumanGateDecision,
    QualityCheckResult,
    QualityCheckStatus,
    ReviewPolicy,
    RiskStatus,
    ToolchainChangeStatus,
    TrafficLight,
)

__all__ = [
    "AuthorizationGrant",
    "AuthorizationId",
    "ChangeSurfaceStatus",
    "EvaluationOutcome",
    "GateEvaluation",
    "GateReason",
    "GateReasonCode",
    "GateReasonKind",
    "GateRevisionRef",
    "GovernanceError",
    "HandoverContext",
    "HandoverGate",
    "HandoverGateId",
    "HandoverNotExecutable",
    "HandoverPolicy",
    "HumanApprovalDecision",
    "HumanApprovalValue",
    "HumanChoiceDecision",
    "HumanDecisionId",
    "HumanGateDecision",
    "InvalidGateSet",
    "InvalidHandoverContext",
    "QualityCheckResult",
    "QualityCheckStatus",
    "ReviewPolicy",
    "RiskStatus",
    "ToolchainChangeStatus",
    "TrafficLight",
    "evaluate_handover_gates",
    "execute_handover",
]
